version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME:-laravel}-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: ${APP_NAME:-laravel}-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_USER: ${DB_USERNAME:-laravel}
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3307:3307"
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME:-laravel}-nginx
        restart: unless-stopped
        ports:
            - "${APP_PORT:-8002}:82"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel-network
        depends_on:
            - app

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
